  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTICULOS_EXACTA_V" ("ID_ARTICULO", "ID_INVENTARIO", "ID_CATEGORIA", "ID_TERMINO", "ID_COLOR_ART", "ID_ESTADO_ART", "NOMBRE_ART", "DESCRIPCION_ART", "MATERIAL_ART", "TITULO", "INV_PDF") AS 
  SELECT
    A.ID_ARTICULO,
    A.ID_INVENTARIO,
    A.ID_CATEGORIA,
    A.ID_TERMINO,
    A.ID_COLOR_ART,
    A.ID_ESTADO_ART,
    A.NOMBRE_ART,
    A.DESCRIPCION_ART,
    A.MATERIAL_ART,
    I.TITULO,
    I.INV_PDF
FROM ARTICULOS A
JOIN INVENTARIOS I ON A.ID_INVENTARIO = I.ID_INVENTARIO;

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ARTICULOS_SEARCH_V" ("ID_ARTICULO", "ID_INVENTARIO", "ID_CATEGORIA", "ID_TERMINO", "ID_COLOR_ART", "ID_ESTADO_ART", "NOMBRE_ART", "DESCRIPCION_ART", "MATERIAL_ART", "TITULO", "INV_PDF", "TONOS_COLOR") AS 
  SELECT DISTINCT
    A.ID_ARTICULO,
    A.ID_INVENTARIO,
    A.ID_CATEGORIA,
    A.ID_TERMINO,
    A.ID_COLOR_ART,
    A.ID_ESTADO_ART,
    A.NOMBRE_ART,
    A.DESCRIPCION_ART,
    A.MATERIAL_ART,
    I.TITULO,
    I.INV_PDF,
    (SELECT LISTAGG(CT.NOM_COLOR_TONO, ' ') 
     WITHIN GROUP (ORDER BY CT.NOM_COLOR_TONO)
     FROM COLORES_TONOS CT
     WHERE CT.ID_COLOR = A.ID_COLOR_ART) AS TONOS_COLOR
FROM ARTICULOS A
JOIN VARIANTES V ON A.ID_TERMINO = V.ID_TERMINO
JOIN INVENTARIOS I ON A.ID_INVENTARIO = I.ID_INVENTARIO;